trigger:
- master

pool:
   vmImage: 'windows-latest'

stages:
  - stage: build
    jobs:
    - job: BuildArtifact
      displayName: Build
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(System.DefaultWorkingDirectory)'
          Contents : |
            **
            |.github/**
            |.git/**
            |*.md
          TargetFolder: '$(Build.ArtifactStagingDirectory)'    
          CleanTargetFolder: true
          Overwrite: true
      -  task: PublishBuildArtifacts@1
         inputs:
           PathToPublish: '$(Build.ArtifactStagingDirectory)'
           ArtifactName: 'drop'
           publishLocation: 'Container'  
